# Generated by Django 5.0.3 on 2024-03-16 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carehomes', '0001_initial'),
        ('company_settings', '0001_initial'),
        ('residents', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Invoice Number')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('carehome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_care_home', to='carehomes.carehome')),
                ('company_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_company_setting', to='company_settings.companysetting')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_invoice', to='invoices.invoice')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_resident', to='residents.resident')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_service', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='invoice_items', to='invoices.invoiceitem'),
        ),
    ]
