# Generated by Django 5.0.3 on 2024-03-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company Name')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sort Code')),
                ('acc_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Account Number')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
