# Generated by Django 5.0.3 on 2024-03-16 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carehomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Title')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email Address')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('carehome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carehomes.carehome')),
            ],
            options={
                'verbose_name': 'Resident',
            },
        ),
    ]
